apiVersion: 1

datasources:
  - name: RuntimeInfluxDBv1
    type: influxdb
    access: proxy
    url: http://influx_database_v1-rt:8086
    database: submodel-db
    user: fluid40
    jsonData:
        tlsAuth: false
        tlsAuthWithCACert: false
    secureJsonData:
      tlsCACert: ""
      tlsClientCert: ""
      tlsClientKey: ""
      password: wbEx!S!#4OHcN!5X
    isDefault: true
    editable: false
    version: 1

  - name: RuntimeInfluxDBv2
    uid: influxdb-v2
    type: influxdb
    access: proxy
    url: http://influx_database_v2-rt:8086
    jsonData:
      version: Flux
      organization: fluid40-org
      defaultBucket: fluid40-bucket
      tlsSkipVerify: false
    secureJsonData:
      token: wbEx!S!#4OHcN!5X
